# Generated by Django 5.2.7 on 2025-11-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='number_of_people',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='test@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default='test@gmail.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='seats',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
